transform:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROJECT', env_var('GOOGLE_CLOUD_PROJECT')) }}"
      dataset: "{{ env_var('DBT_SILVER', 'silver') }}"
      location: "{{ env_var('REGION', 'europe-north2') }}"
      priority: interactive
      threads: 4
