substitutions:
  _REGION: europe-north2
  _REPO:   starfish-docker

steps:
- id: build
  name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/transform-dbt:$SHORT_SHA
    - -t
    - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/transform-dbt:latest
    - .

- id: push-sha
  name: gcr.io/cloud-builders/docker
  args: ["push","$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/transform-dbt:$SHORT_SHA"]

- id: push-latest
  name: gcr.io/cloud-builders/docker
  args: ["push","$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/transform-dbt:latest"]
