name: "transform"
version: "1.0.0"
config-version: 2

profile: "transform"

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]  # unused now (no CSV), but harmless

models:
  transform:
    +materialized: view

    silver:
      +schema: "{{ env_var('DBT_SILVER', 'silver') }}"
      +materialized: view

    gold:
      +schema: "{{ env_var('DBT_GOLD', 'gold') }}"
      +materialized: view
